variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - test
  - release

# JOBS

# Check for PEP8 issues
test-pep8:
  stage: test
  image: apihackers/flake8
  script:
    - flake8
  tags:
    - docker

# Build a docker image for an RT-RAMSIS release and push it to the registry
release:
  stage: release
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build
      --build-arg GITLAB_USER=gitlab-ci-token
      --build-arg GITLAB_PW=$CI_JOB_TOKEN
      --tag $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - docker push
  when: manual
  only:
    - tags
    - master
  tags:
    - docker

# Deploy to production machine
deploy-production:
  stage: release
  variables:
    DEPLOY_PATH: /opt/ramsis/$CI_COMMIT_REF_SLUG
  script:
    - virtualenv $DEPLOY_PATH/venv
    - source $DEPLOY_PATH/venv/bin/activate
    - pip install -r requirements.txt
    - pip install .
    - ln -s $DEPLOY_PATH /ramsis/current
  tags:
    - production