language: python
before_script:
- pip install tox

# test script
script:  tox -e ${TOX_ENV}
notifications:
  on_success: change
  on_failure: always

env:
  matrix:
#  - TOX_ENV=py26
#  - TOX_ENV=py27
#  - TOX_ENV=py32
#  - TOX_ENV=py33
#  - TOX_ENV=py34
#  - TOX_ENV=pypy
  - TOX_ENV=py27-flake8
#  - TOX_ENV=py34-flake8