variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  TEST_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

# JOBS

build:
  stage: build
  script:
    # Try to pull the latest release image to use it as a cache source
    - docker pull $RELEASE_IMAGE_TAG || true
    - docker build
      --cache-from $RELEASE_IMAGE_TAG
      --build-arg GITLAB_USER=gitlab-ci-token
      --build-arg GITLAB_PASSWORD=$CI_JOB_TOKEN
      --tag $TEST_IMAGE_TAG
    - docker push $TEST_IMAGE_TAG

test-pep8:
  stage: test
  image: $TEST_IMAGE_TAG
  before_script:
    - pip install flake8
  script:
    - flake8

deploy-production:
  stage: deploy
  script:
    - docker pull $TEST_IMAGE_TAG
    - docker tag $TEST_IMAGE_TAG $RELEASE_IMAGE_TAG
    - docker push $RELEASE_IMAGE_TAG
  only:
    - master
