variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  TEST_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

# JOBS

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE_TAG .
    - docker push $TEST_IMAGE_TAG

test-pep8:
  stage: test
  image: $TEST_IMAGE_TAG
  before_script:
    - pip install flake8
  script:
    - cd /ramsis
    - flake8

deploy-production:
  stage: deploy
  script:
    - docker pull $TEST_IMAGE_TAG
    - docker tag $TEST_IMAGE_TAG $RELEASE_IMAGE_TAG
    - docker push $RELEASE_IMAGE_TAG
  only:
    - master
