variables:
  REGISTRY: "gitlab.seismo.ethz.ch:4567"

stages:
  - build
  - test
  - deploy

# JOBS

build:
  stage: build
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker build -t $REGISTRY/indu/rt-ramsis .
    - docker push $REGISTRY/indu/rt-ramsis
#  Only run this on runners with the 'docker' tag
#  tags:
#    - docker

flake8:
  stage: test
  before_script:
    - pip install flake8
  script:
    - cd RAMSIS
    - flake8

#nosetests:
#  stage: test
#  script:
#    - cd ramsis
#    - nosetests


deploy:
  stage: deploy
  when: manual
  script:
    - sleep 5

